# ------------------------------------------------------------------------
# Configurações de Adequação do Desenvolvedor para a PoC do Sonar
# ------------------------------------------------------------------------
sonar.organization=gonntt
sonar.sources=.
sonar.exclusions=**/tests/**,**/notebooks/teste.py