# ------------------------------------------------------------------------
# Configurações de Adequação do Desenvolvedor para o SonarCloud
# ------------------------------------------------------------------------
sonar.organization=gonntt
sonar.projectKey=DATAOPS-pipeline-vendas
sonar.sources=.
sonar.exclusions=**/tests/**,**/notebooks/teste.py