# ------------------------------------------------------------------------
# Configurações Oficiais de Adequação para o SonarCloud
# ------------------------------------------------------------------------
sonar.organization=gonntt

# Forçamos a chave EXATA que o SonarCloud gerou na tela para você:
sonar.projectKey=gonntt_NomeProjeto_Databricks_nprd

# Escopo de análise
sonar.sources=.
sonar.exclusions=**/tests/**,**/notebooks/teste.py