name: call-qa-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-qa:
    permissions:
      id-token: write
      contents: read
    environment: nprd
    uses: gonntt/devsecops---solution/.github/workflows/qa-pipeline.yml@main
    with:
      environment: nprd
      sistema: "NomeProjeto_Databricks_nprd"
      sigla: "gonntt"
      componente: "NomeProjeto_Databricks_nprd"
    secrets: inherit