name: call-dataops-pipeline

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  call-dataops:
    uses: gonntt/devsecops---solution/.github/workflows/dataops-pipeline.yml@main
    with:
      environment: nprd
      # PASSAMOS A INFORMAÇÃO EXATA AQUI:
      keyvault_name: 'kvdataops'
      secret_client_id_name: 'databricks-sp-client-id'
      secret_client_secret_name: 'databricks-sp-client-secret'
    secrets: inherit